Traceback (most recent call last):
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/qianahunt/anaconda3/envs/jupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
M101_CSC['1Sig'] = sig1  # Saves sig1 to a new header called '1Sig'
M101_CSC['2Sig'] = sig2  # Saves sig2 to a new header called '2Sig'
display(M101_CSC)

M101_CSC.to_csv('M101_csc_astrocorrected.frame')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 1[0m
[0;32m----> 1[0m M101_CSC[[38;5;124m'[39m[38;5;124m1Sig[39m[38;5;124m'[39m] [38;5;241m=[39m [43msig1[49m  [38;5;66;03m# Saves sig1 to a new header called '1Sig'[39;00m
[1;32m      2[0m M101_CSC[[38;5;124m'[39m[38;5;124m2Sig[39m[38;5;124m'[39m] [38;5;241m=[39m sig2  [38;5;66;03m# Saves sig2 to a new header called '2Sig'[39;00m
[1;32m      3[0m display(M101_CSC)

[0;31mNameError[0m: name 'sig1' is not defined

